---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
---

```{r}
library(tidyverse)
```


```{r}
college_grad <- read_csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/college-majors/recent-grads.csv")

view(college_grad)
```

```{r}
college_grad %>% 
    mutate(Major_category = fct_reorder(Major_category, Median)) %>%
    ggplot(aes(Major_category, Median)) + 
    geom_boxplot() +
    scale_y_continuous(labels = scales::dollar_format()) +
    coord_flip()
```

### Here is the categories that make a lot money upon graduation

```{r}
college_grad %>% 
    group_by(Major_category) %>%
    summarize(Median = median(Median)) %>%
    mutate(Major_category = fct_reorder(Major_category, Median)) %>%
    ggplot(aes(Major_category, Median)) + 
    geom_col() +
    scale_y_continuous(labels = scales::dollar_format()) +
    coord_flip()
```

### Here, we will find the highest top earning majors

```{r}
Majors <- college_grad %>%
    arrange(desc(Median)) %>%
    select(Major, Major_category, Median, P25th, P75th, Sample_size)  %>%
    mutate(Major = fct_reorder(Major, Median)) 

Majors %>% head(20) %>%
    ggplot(aes(Major, Median,, color = Major_category)) +
    geom_point() +
    coord_flip()
```

### The lowest earning Majors

```{r}
college_grad %>%
    arrange(desc(Median)) %>%
    select(Major, Major_category, Median, P25th, P75th)  %>%
    tail(20) %>%
    
    mutate(Major = fct_reorder(Major, Median)) %>%
    ggplot(aes(Major, Median,, color = Major_category)) +
    geom_jitter() +
    coord_flip()
```

```{r}
# Majors  %>%
#     ggplot(aes(Sample_size, Median)) +
#     geom_point() +
#     scale_x_log10()

# install.packages("tm")           # for text mining 
# install.packages("SnowballC")    # for text stemming 
# install.packages("wordcloud")    # word-cloud generator 
# install.packages("RColorBrewer") # color palettes 
   
# Load the packages 
# library("tm") 
# library("SnowballC") 
# library("wordcloud") 
# library("RColorBrewer")
# wordcloud(words = Majors$Major_category,  
#           freq = Majors$Median, 
#           min.freq = 1,  
#           max.words =200, 
#           random.order = TRUE,  
#           rot.per = 0.35,  
#           colors = brewer.pal(8, "Dark2")) 


`````

### Most common majors :

```{r}
college_grad %>%
    count(Major_category, wt = Total, sort = TRUE) %>%
    mutate(Major_category = fct_reorder(Major_category,n)) %>%
    ggplot(aes(Major_category, n, fill = Major_category)) +
    theme(legend.position = "none") +
    geom_col() +
    coord_flip() +
    scale_y_continuous(labels = scales::dollar_format()) +
    labs(y = "Total  number of graduates")
```


```{r}
college_grad %>%
    mutate(Major_category = fct_reorder(Major_category, Total)) %>%
    #count(Major_category, wt = Total, sort = TRUE) %>%
    gather(Gender, Number, Men, Women) %>%
    arrange(desc(Major_category)) %>% 
    
    ggplot(aes(Major_category,Total, fill = Gender)) +
    #theme(legend.position = "none") +
    geom_col() +
    coord_flip() +
    scale_y_continuous(labels = scales::number_format()) +
    labs(y = "Total  number of graduates")
```


### which gender earn more money based on top Major

```{r}
college_grad %>%
    arrange(desc(Total)) %>%
    head(20) %>%
    mutate(Major = fct_reorder(Major, Total)) %>%
    gather(Gender, Number, Men, Women) %>%
    select(Major, Gender, Number) %>%
    
    
    ggplot(aes(Major, Number, fill = Gender)) +
    geom_col() +
    scale_y_continuous(labels = scales::dollar_format()) +
    coord_flip()
```


```{r}
college_grad %>%
    group_by(Major_category, Median) %>%
    summarize_at(vars(Total, Men, Women), sum, na.rm=TRUE) %>%
    mutate(ShareWomen = Women/Total) %>%
    arrange(desc(ShareWomen)) %>%
    
    ggplot(aes(ShareWomen, Median, color = Major_category)) +
    geom_jitter() +
    scale_y_continuous(labels = scales::dollar_format()) 

```

### Total Major in each major's category
```{r}
college_grad %>%
    select(Major, Major_category, Total, ShareWomen, Sample_size, Median) %>%
    add_count(Major_category) %>%
    filter(n >= 10) %>%
    count(Major_category) %>%
    arrange(desc(n))
```

### Predict the median of ShareWomen 




